# Generated by Django 3.2.6 on 2021-08-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Fikrlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fikri', models.TextField()),
                ('ism_familiyasi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('lavozimi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jamoamiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiyasi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('lavozimi', models.CharField(max_length=100)),
                ('telefon_raqami', models.CharField(max_length=100)),
                ('telegram_manzili', models.CharField(max_length=100)),
                ('instagram_manzili', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot', models.TextField()),
                ('joyi', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('telefon_raqami', models.CharField(max_length=100)),
                ('telegram_manzili', models.CharField(max_length=100)),
                ('instagram_manzili', models.CharField(max_length=100)),
                ('youtube_manzili', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaidCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('seats', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('money', models.IntegerField()),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
