# Generated by Django 3.2.6 on 2021-08-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('seats', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('money', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
