# Generated by Django 3.2.6 on 2021-08-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_paidcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fikrlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fikri', models.TextField()),
                ('ism_familiyasi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('lavozimi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jamoamiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiyasi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('lavozimi', models.CharField(max_length=100)),
                ('telefon_raqami', models.IntegerField()),
                ('telegram_manzili', models.CharField(max_length=100)),
                ('instagram_manzili', models.CharField(max_length=100)),
            ],
        ),
    ]
