# Generated by Django 3.2.6 on 2021-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_fikrlar_jamoamiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamoamiz',
            name='telefon_raqami',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paidcourse',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
