# Generated by Django 3.2.6 on 2021-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210808_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot', models.TextField()),
                ('joyi', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('telefon_raqami', models.CharField(max_length=100)),
                ('telegram_manzili', models.CharField(max_length=100)),
                ('instagram_manzili', models.CharField(max_length=100)),
                ('youtube_manzili', models.CharField(max_length=100)),
            ],
        ),
    ]
